### ISSUE TITLE
Node-red crashed after connect Arduino and using this module

### ISSUE THREAD

**Issue by ghost** [node-red/node-red-nodes#920]
### Which node are you reporting an issue on?
node-red-node-arduino
### What are the steps to reproduce?
1. Use Arduino Input
2. Connect Arduino
### What happens?
Node-red crashed with error: `TypeError: cannot set properties of undefined (setting 'pinMode') at Firmata.pinMode (/root/.node-red/node_modules/firmata-io/lib/firmata.js:947:27)`
### What do you expect to happen?
Successful read from pin
### Please tell us about your environment:

- [ ] Node-RED version: 2.2.2
- [ ] node.js version: v16.14.2
- [ ] npm version: 8.1.3
- [ ] Platform/OS: armv7/ Alpine Linux
- [ ] Browser: Yandex Browser (on other PC with Windows)

**Comment by PizzaProgram** [comment]
I can confirm this bug.

To reproduce:
 - Set an invalid pin number and mode to: Analog 

Node-red will crash.

## Solution:
1. The code should first check, if pin number is valid, before applying MODE
2. Put a `try..catch` around  `pinMode` change. _(If setting the mode fails. Because it does sometimes!)_

Probably other modes + invalid pin numbers should be checked too.

**Comment by dceejay** [comment]
Much improved error handling now in v1.1.0
Reports invalid pin, and also port not found.

**Comment by PizzaProgram** [comment]
@dceejay Great to hear!
Currently on npm only 1.0.0 is available.  _( The one from 1 year, 3 months ago )_

**Comment by PizzaProgram** [comment]
@dceejay  Is there any way the new 1.1.0 version is getting uploaded to NPM?

**Comment by PizzaProgram** [comment]
You are right! Had to re-open NR window. Now it's visible.

![Image](https://github.com/user-attachments/assets/57f02f13-1158-4aaa-bede-012a80720b5b)

Will test it in the next few weeks.

**Comment by PizzaProgram** [comment]
# Problem 1 : 
at `35-arduino.js` line 176 : 
```js
if (node.pin && !isNaN(node.pin) && node.pin >=0 && node.pin <= 20) {
...
```

`20` is wrong! It should be a number queried from  `queryCapabilities()` function, called by `firmata-io.js` once !
_For example:_ RPi Pico with customFirmata has: `TOTAL_PINS = 30` but not all digital.
See here: https://github.com/firmata/ConfigurableFirmata/issues/115#issuecomment-2633239628

## The Result is:
 I can not use all the ports, including built-in LED `pin=25`, since I've upgraded to v1.1.

**Comment by PizzaProgram** [comment]
IMHO the whole naming of the module is wrong.
Instead of "Arduino" we should start a new, universal node, called:

## node-red-node-firmata

**Comment by PizzaProgram** [comment]
> We could of course create a new one - subject to latest naming conventions of course

I agree ! We should. This should be **the** universal communication protocol that should be on the main menu of NR's website, compatible with all boards supporting firmata. _(not limited to arduino, supporting extended capabilities, etc.)_

> But a Pull Request along the lines you suggest would be gratefully accepted.

I'm still trying to figure out, how to get values of the pins, previously set by the  `queryCapabilities()` function.
So far I've found these:
1. A way checking, if an analogue pin is valid:  `if (board.pins[board.analogPins[pin]]) { ... } `
2. Maybe this should be ok, for normal pins:  
  ` if (node.pin && !isNaN(node.pin) && node.pin >=0 && node.pin <= node.board.pins.length) {  ` 

_(PS: I "just" have to test it, but always getting confused about npm link and rebuild ... )_

**Comment by dceejay** [comment]
You shouldn't need either link or rebuild. If you have the code in a directory then from your .node-red user directory just npm install {path to directory} will install it. You only need to do that once

**Comment by PizzaProgram** [comment]
### Things that are fixed / added: `v1.2`
1. max pin problem solved
2. analogue pin checking! (NR crashed before) 
3. help added to html
4. `msg.payload = reset` >> resets board  (not yet working 👎 )
5. added many `else` and constants to speed up execution
6. renamed variables to be unique. Like: node -> `brdNode`, `nodeIn`, `nodeOut`
7. added error handling for unhandled errors
8. changed `var` to `let` everywhere

_(Worked ca 30-40 hours so far on it.)_
Please reopen this Issue, so others can see the progress too.
... too tired to create a Commit now. Here are the changed files:

[node-red-node-arduino.zip](https://github.com/user-attachments/files/19154182/node-red-node-arduino.zip)

## Needs to be solved (in `v1.3`)
[ ]. `startup()` function is running min. 2x !
   _(sometimes continuously every 5000ms .. especially if there is min 1 node with wrong pin)_ 
[ ]. Dual startup of wrong pin overrides the "wrong pin" status msg. "Connecting..." appears. 
[]. There are 3 different `startup()` loops. Probably conflicting each other. Needs more investigation.
[]. [Flow Restart] kills communication. Board does not reset on close
[]. [Partial deploy] does not work. 

> subject to latest naming conventions of course

What are those? Any link to it?

**Comment by dceejay** [comment]
No need for renaming unless you plan to release a new node.  Great if we can fix this one with v1.2 (or 1.3 etc)

**Comment by PizzaProgram** [comment]
> No need for renaming 

The goal would be to have a universal name that refers to all boards running Firmata, not just "Arduino".

There are many board types available:
- [Arduino compatible](https://en.wikipedia.org/wiki/List_of_Arduino_boards_and_compatible_systems) (any device that can run [Firmata](http://firmatabuilder.com/)).
-   [Raspberry Pi Pico](https://www.raspberrypi.com/products/raspberry-pi-pico/) (Firmata over serial, Wifi?).
-   [ESP8266](https://www.espressif.com/en/products/socs/esp8266) (Firmata over Serial, Bluetooth or WiFi).
-   [ESP32](https://www.espressif.com/en/products/socs/esp32) 

So, the name "Arduino" is misleading.

**Comment by PizzaProgram** [comment]
Today, I've listed the values of the `firmata.board` and found this:

![Image](https://github.com/user-attachments/assets/7898d908-a96b-45c4-a5e9-9b2b5da05ce4)

You have created 1-1 loop for in/out nodes and those are calling `startup()` function every 4500ms.
And I think that is creating a **new** instance every ~5secs here:
```js
if (nodeIn.board.isReady) { doit(); }
else { nodeIn.board.once("ready", function() { doit(); }); }
```
I will try to figure out, how to prevent that.

**Comment by PizzaProgram** [comment]
An other interesting thing is:
 - I've fixed the `.reset` function, which should theoretically restart the board on re-DEPLOY / flow-restart.

Conclusion:
### It seems to do nothing !

Maybe `ConfigurableFirmata` is not executing the `const SYSTEM_RESET = 0xff;` command ?

[Restart flow] still kills the communication. 👎 >> Port not found message appears everywhere.
Like if the serial port is not closed properly.

**Comment by PizzaProgram** [comment]
## Current progress:

Some problems fixed, but many things can not be fixed unless I completely refactor the whole code-structure.
Here is my current (half-)state of code. _(NOT WORKING! Do not use in prod. environment!)_

[node-red-node-arduino-1.2.1.zip](https://github.com/user-attachments/files/19235324/node-red-node-arduino-1.2.1.zip)

**Comment by PizzaProgram** [comment]
"Progress" update:
 - refactored the whole code
 - changed the "main creation" of the board to the recommended way using firmata showing: [here ...](https://github.com/yokobond/firmata-io) at the examples
 - changed it back, because it did not work as I've expected (Opened a [ticket](https://github.com/yokobond/firmata-io/issues/1) for it)
 - managed to [set up](https://discourse.nodered.org/t/how-to-set-up-vscode-for-developing-node-red-nodes/92853/6?u=pizzaprogram) a debugging environment (VSC)
 - still fixing errors and bugs, learning about node.js tricky things (like Null / undefined comparisons, emitters, etc)
 - added emit 
 - created status definitions like:
```js
const BdStates = Object.freeze({                // (freeze = immutable record)
    permanentError: -9,
    portNotSet    : -3, // no COM-port specified
    disconnected  : -2,
    tryReconnect  : -1,
    start         :  0,
    connecting    :  1,
    gettingVersion:  2,
    OK            :  3
});
```
... etc.

**Comment by PizzaProgram** [comment]
Progress at 90% :

- fixed HTML bugs _(number inputs for pin instead of text, min-max, added more tips & warning, etc...)_
- added: Startup sampling-interval value to set. _(Sadly, has no effect yet.)_
- added: log2consol
- Deploy works !
- Partial deploy works also!! 🥇 Even changing 1-1 pin during run without stopping or restart.
- The .reset function, which restarts the board is working ! Also at re-deploy.
- msg.payload null warning for Out-node input
- added new Out-node types: `[RESET, INTERVAL]`

## TODO:

- fix: Sampling-interval at startup
- too much emitters! _(need to investigate, how to do it properly with master/children)_
- fix: status not showing under nodes

**Comment by PizzaProgram** [comment]
### Current state:
![Image](https://github.com/user-attachments/assets/76f21679-a161-47d7-867a-d8bfd0aaefbc)

### Current board view:

![Image](https://github.com/user-attachments/assets/c101bc75-a5dd-434c-a0aa-cb462cb45e67)

## TODO 1.4 
_(rather a whishlist, because maybe I won't have enough time for all of these)_
- **flushDigitalPorts()** = setting array of ports at once, not one-by-one
- **queryPinState()** vs. digitalRead()  ... at startup? Need to investigate
- **Firmware-Name:** show board name on Node-RED panel, which was set at firmata firmware at startup:
    ```c
    void setup() {
      Firmata.setFirmwareNameAndVersion("my-unique-ArduinoFirmata-name-42", FIRMATA_PROTOCOL_MAJOR_VERSION, FIRMATA_FIRMWARE_MINOR_VERSION)`
    ``` 
- **FindByName:** use this name for auto-search this unique board at startup,
    _no matter which serial-port is it plugged_

**Comment by PizzaProgram** [comment]
I'm finally at the finish line with v1.3  :-)

- most of Event / emit exceed limit problems **solved!**
- status icons and lines under nodes are finally working stable.
  ![Image](https://github.com/user-attachments/assets/c5751cf2-ec44-4b33-938d-edb3ece90a55)

- better naming / label showing
- can handle "no board" / "no com set" / "no pin set"
- more html fixed + tips added + rearranged on setup panels
- more console-logs (can be turned off)
- **sampling interval** can be set ! 👍 
    -  Both at startup + at runtime !
- able to **reset** the board during runtime 👍
    - Both with pre-set type + with: `msg.payload = reset`
- endless "search" animation probably solved. (need testing!)

## Need to finish at v1.3.3 before final release:
1. unplug-replug should restart everything
2. add samples
3. One more emit problem left:    > MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ready listeners added to [Firmata]

[node-red-node-arduino_v1.3.0.zip](https://github.com/user-attachments/files/19382073/node-red-node-arduino_v1.3.0.zip)

**Comment by PizzaProgram** [comment]
## Finished 1.3.3 STABLE:

[node-red-node-arduino_v1.3.3.zip](https://github.com/user-attachments/files/19515074/node-red-node-arduino_v1.3.3.zip)

1. if board gets only **later** plugged in (after start) >> it works too!
2. Listener (multi-event) problem solved fully !!!
3. new: **auto-pin-conflict search** and show system
4. **version** is shown at in+out config panel
5. even more **comment** lines in code
6. more HTML enhancements on config panels
7. all kinds of bug fixes ...

### Still **not** working perfectly:
- **Re-plugged** board <- after unplug during run 
    _(needs flow restart to work again)_

Will create a commit from these new files, and open a new topic about it at NR forum.

**Comment by PizzaProgram** [comment]
Ti finish the list, I write it down here too:
 v1.3.3 had still some tiny bugs, _(like: crashed at line: `done()` on flow-restart while closing the node,)_ but: 
 **v1.3.4-20250331 is STABLE.**

Also auto-port search is fixed too !
New [commit + Pull req. is here...](https://github.com/node-red/node-red-nodes/pull/1092)

**Comment by dceejay** [comment]
Thanks to @PizzaProgram's extensive fixes and PR - new version v1.4.0 now released.

**Comment by PizzaProgram** [comment]
Why 1.4.0?  
 - did you change something else on it?
 - do I have to check line by line?
 - why didn't you upload 'firmata-io.js' changes ?

I've found 3 more logical things to fix.
- Reported "pin conflict" at "String", "sampling rate", etc. types too.
- Reported "wrong pin" at "String-in" type. _(strings do not use Pins)_
- String-in node can start before board-report. _(no need to wait)_

Fixed them.

Will make a push soon.

**Comment by PizzaProgram** [comment]
I've also noticed you have deleted lines / not updated at 35-arduino.json.

And since you have changed the version numbering, it will be inconsistent with the panel.

Also it conflicts with pronounced future version plans I wrote about [here](https://github.com/node-red/node-red-nodes/issues/920#issuecomment-2735208317) as "Todo 1.4" .

# OFF
I do not know what to say any more. 1.4.1 will be my last upload, and I've finished to work "under you".
Can not bare any more stress and all the extra hours I had to invest arguing with you + finding errors you have made.

**Comment by dceejay** [comment]
Hi, @PizzaProgram many apologies for any stress. I have been travelling for the last month with only short time access to laptop and so rushed in the updates and messed up. That was not my intention but in trying to untangle the mess of merging your 1.3.0 version rather than 1.3.1 I missed some parts. I will try to rectify. If you can point me at your 1.4.1 I will compare with that.

**Comment by PizzaProgram** [comment]
It is (sadly) not possible via web-interface of Github to upload files into different libraries and create ONE pull req. from all of those.
So it was 2 pull req. But do not worry, I will create a brand new with v1.4.1 .

> many apologies for any stress.

No problem.
